-- 1.
SELECT JOB, EMPNO, ENAME, SAL, D.DEPTNO, D.DNAME
  FROM EMP E, DEPT D
  WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME = 'ALLEN')
    AND E.DEPTNO = D.DEPTNO;
    
-- 2.
SELECT EMPNO, ENAME, DNAME, HIREDATE, LOC, SAL, GRADE
  FROM EMP E, DEPT D, SALGRADE S
  WHERE SAL > ALL (SELECT AVG(SAL) FROM EMP)
  AND E.DEPTNO = D.DEPTNO
  AND E.SAL BETWEEN LOSAL AND HISAL
  ORDER BY SAL DESC, EMPNO;
  
-- 3. 
SELECT EMPNO, ENAME, JOB, E.DEPTNO, DNAME, LOC
  FROM EMP E, DEPT D
  WHERE E.DEPTNO = D.DEPTNO
  AND D.DEPTNO = 10
  AND JOB != ALL (SELECT JOB FROM EMP WHERE DEPTNO = 30);

-- 4.1(다중행 함수 사용O)
SELECT EMPNO, ENAME, SAL, GRADE
  FROM EMP E, SALGRADE S
  WHERE E.SAL > ALL (SELECT SAL FROM EMP WHERE JOB = 'SALESMAN')
  AND SAL BETWEEN LOSAL AND HISAL
  ORDER BY EMPNO;

--4.2 (다중행 함수 사용X)
SELECT EMPNO, ENAME, SAL, GRADE
  FROM EMP E, SALGRADE S
   WHERE E.SAL > (SELECT MAX(SAL) FROM EMP WHERE JOB = 'SALESMAN')
   AND SAL BETWEEN LOSAL AND HISAL
  ORDER BY EMPNO;

SELECT MAX(SAL) FROM EMP WHERE JOB = 'SALESMAN';
SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;